### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/trower-base64#17]
Also have to change references to the branch in .travis.yml, README, and CONTRIBUTING. Double check any other markdown files as well - sometimes links have the branch name in them.

**Comment by greenfoo** [comment]
Just as a data point for others that might be considering a similar change in other repositories in the future, let me say that this has caused some trouble in our infrastructure today.

Yocto feeds make use of this repo and... well... all our nightly builds failed today and we are still figuring out a way to fix this while maintaining backwards compatibility with older branches of our project.

To others reading this: please consider not applying this change to existing repositories, but only to newly created ones :)

**Comment by schmidtw** [comment]
@greenfoo are you able to move to use the released versions of the code objects (which are released with specific sha256sum values to prevent the issues with unstable checksums from github)?

Upon reviewing options as of late this change looked like it would not be a major issue:
https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/

**Comment by greenfoo** [comment]
@schmidtw we are reviewing changes to upstream Yocto to change their references to sha256sums instead of named branches. That should fix the issue once they merge the change and we sync our trees.

Thanks.

PS: I was just making a warning about the possible unforeseen consequences a change such as this one might have in case others are considering a similar naming update :)

**Comment by schmidtw** [comment]
We very much would like to update the rest of the c based project branches in xmidt-org, but would ideally like to do so without breaking users.

Do you have any suggestions on how we could communicate the changes are coming & enable you to change to releases before removing the branch?

**Comment by greenfoo** [comment]
I'm afraid I cannot think of anything.

We did not even know we were using this repo until one build script from a different repo which was being pulled from a third one broke!

Maybe there is a way of using GitHub's API to find out which other repos are using this one... and which ones are using those ones... and so on (??)... and then create an issue in those repos making an announcement about the future naming convention change?

Sorry for not being more helpful.

**Comment by schmidtw** [comment]
I apologize both for the break & your lost time.  I do appreciate your feedback.  At a minimum when we post the schedule for changes for the other repos, I'll '@' you so you're alerted & we can hopefully avoid a break.

**Comment by greenfoo** [comment]
Thanks :)
