### ISSUE TITLE
 master to main creating fetch issues with yocto recipes as it still using default branch as master

### ISSUE THREAD

**Issue by pavannandyala** [xmidt-org/trower-base64#29]
Fetch failures observed with yocto recipes if we rename master to main

ERROR: trower-base64-git+AUTOINC+fbb9440ae2-r0 do_fetch: Fetcher failure: Unable to find revision fbb9440ae2bc1118866baefcea7ff814f16613dd in branch master even from upstream
ERROR: trower-base64-git+AUTOINC+fbb9440ae2-r0 do_fetch: Fetcher failure for URL: 'git://github.com/Comcast/trower-base64.git'. Unable to fetch URL from any source.
ERROR: trower-base64-git+AUTOINC+fbb9440ae2-r0 do_fetch: Function failed: base_do_fetch

**Comment by schmidtw** [comment]
I'm not sure what yocto is doing in this case as I can perform a clone & checkout without problem:

**Clone:**
```
git clone git://github.com/Comcast/trower-base64.git
Cloning into 'trower-base64'...
remote: Enumerating objects: 396, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 396 (delta 88), reused 137 (delta 53), pack-reused 208
Receiving objects: 100% (396/396), 168.24 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (197/197), done.
```

**Checkout:**
```git checkout fbb9440ae2bc1118866baefcea7ff814f16613dd
Note: switching to 'fbb9440ae2bc1118866baefcea7ff814f16613dd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at fbb9440 Merge pull request #11 from cableramki/master
```

If you change the url to `git://github.com/Comcast/trower-base64.git;branch=main` it has been reported to resolve the yocto issue.  Do note that the URL is not accurate as the repository moved to here some time ago: `git://github.com/xmidt-org/trower-base64.git`

**Comment by pavannandyala** [comment]
SUMMARY = "C implementation of base64 encode/decode"
HOMEPAGE = "https://github.com/Comcast/trower-base64"
SECTION = "libs"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=b1e01b26bacfc2232046c90a330332b3"
SRCREV = "fbb9440ae2bc1118866baefcea7ff814f16613dd"
SRC_URI = "git://github.com/Comcast/trower-base64.git"
PV = "git+${SRCPV}"
S = "${WORKDIR}/git"
inherit pkgconfig cmake
EXTRA_OECMAKE += "-DBUILD_TESTING=OFF"


Above recipe will not work now

**Comment by pavannandyala** [comment]
SUMMARY = "C implementation of base64 encode/decode"
HOMEPAGE = "https://github.com/Comcast/trower-base64"
SECTION = "libs"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=b1e01b26bacfc2232046c90a330332b3"
SRCREV = "fbb9440ae2bc1118866baefcea7ff814f16613dd"
SRC_URI = "git://github.com/Comcast/trower-base64.git"
PV = "git+${SRCPV}"
S = "${WORKDIR}/git"
inherit pkgconfig cmake
EXTRA_OECMAKE += "-DBUILD_TESTING=OFF"



this recipe will not work as branch will default to master

**Comment by schmidtw** [comment]
Based on input I have been given changing:
```
 SRC_URI = "git://github.com/Comcast/trower-base64.git"
```

To :
```
 SRC_URI = "git://github.com/Comcast/trower-base64.git;branch=main"
```

Should resolve that then.  It sounds like yocto's defaulting to master is the issue.

**Comment by pavannandyala** [comment]
Recipe need to be updated is solution
